source 'https://rubygems.org'

gem 'activesupport'
gem 'elasticsearch', '>= 5.0.0'
gem 'elasticsearch-api', '>= 5.0.0'
gem 'elasticsearch-transport', '>= 5.0.0'
gem 'faraday', '>= 0.8.0'
gem 'ffi'
gem 'gli'
gem 'multi_json', '>= 1.9.0'
gem 'rake'