source 'https://rubygems.org'

gem 'activesupport'
gem 'elasticsearch', '>= 5.0.0'
gem 'elasticsearch-api', '>= 5.0.0'
gem 'elasticsearch-transport', '>= 5.0.0'
gem 'ffi', '~> 1.9.14'
gem 'gli', '~> 2.14.0'
gem 'multi_json', '>= 1.9.0'
gem 'rake', '~> 12.0.0'