source 'https://rubygems.org'

gem 'elasticsearch', '>= 1.0.6'
gem 'elasticsearch-api', '>= 1.0.6'
gem 'elasticsearch-transport', '>= 1.0.6'
gem 'multi_json', '>= 1.9.0'
gem 'faraday', '>= 0.8.0'
gem 'activesupport'
gem 'rake'
gem 'thor'
